name: Bug report
description: Create a report to help us improve
labels: [bug]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Have you checked if someone has reported this issue before?
      options:
        - label: I have searched through the AstroNvim docs
          required: true
        - label: I have searched through the existing issues of AstroNvim
          required: true
        - label: I have searched the existing issues of plugins related to this issue
          required: true
  - type: input
    id: neovim-version
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "0.9.1 release"
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: "Operating system/version"
      placeholder: "macOS 11.5"
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: "Terminal/GUI"
      placeholder: "kitty"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add any additional context about the problem here.
