name: Announce releases on the AstroNvim Discord

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK_URL:
        description: "The webhook URL to push to"
        required: true
    inputs:
      plugin_name:
        description: "Name of the neovim plugin"
        required: true
        type: string

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch changelog
        id: changelog
        run: |
          echo 'DISCORD_MESSAGE<<EOF' >> $GITHUB_OUTPUT
          awk '/^## \[/{if (p) exit; p=1} p' CHANGELOG.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Send changlog to Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: "${{ inputs.plugin_name }} Release"
          DISCORD_AVATAR: "https://avatars.githubusercontent.com/u/141652974?v=4"
          DISCORD_EMBEDS: "[]"
        with:
          args: "${{ steps.changelog.outputs.DISCORD_MESSAGE }}"
